#-------------------------------------------------------------------------------------------#
# Ansible Playbook for configuring haproxy for dns & dhcp 
# https://github.com/rovandep/ocp4-lab
#-------------------------------------------------------------------------------------------#

- name: Inject haproxy configuration file
  template: 
    src: files/haproxy_cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    
- name: Enabling haproxy service
  service:
    name: haproxy
    enabled: yes
    state: started 

