#-------------------------------------------------------------------------------------------#
# Ansible Playbook for registering a host and updating the system
# https://github.com/rovandep/ocp4-lab
#-------------------------------------------------------------------------------------------#

- name: 
