#-------------------------------------------------------------------------------------------#
# Ansible Playbook for configuring dnsmasq for dns & dhcp 
# https://github.com/rovandep/ocp4-lab
#-------------------------------------------------------------------------------------------#

- name: fixing permissions
  shell: chmod +r *
  args: 
    chdir: /var/www/html/ocp-installer/{{ clustername }}
    executable: /bin/bash

- name: fixing permissions
  shell: chmod 777 -R tftp
  args: 
    chdir: /var/www/html/
    executable: /bin/bash

- name: Inject dnsmasq configuration file
  template: 
    src: files/dnsmasq_conf.j2
    dest: /etc/dnsmasq.conf
    
- name: Inject hosts configuration file
  template:
    src: files/hosts.j2
    dest: /etc/hosts 

- name: Copy syslinux file for tftp server usage
  copy:
    src: /usr/share/syslinux/
    dest: /var/www/html/tftp/
    remote_src: yes

- name: Inject default pxelinux configuration file
  template:
    src: files/tftp_default.j2
    dest: /var/www/html/tftp/pxelinux.cfg/default

- name: Enabling dnsmasq service
  service:
    name: dnsmasq
    enabled: yes
    state: started 