#-------------------------------------------------------------------------------------------#
# Ansible Playbook for configuring dnsmasq for dns & dhcp 
# https://github.com/rovandep/ocp4-lab
#-------------------------------------------------------------------------------------------#

- name: fixing permissions
  shell: chmod +r *
  args: 
    chdir: /var/www/html/ocp-installer/{{ clustername }}
    executable: /bin/bash

- name: fixing permissions
  shell: chmod 777 -R rhcos
  args: 
    chdir: /var/www/html/
    executable: /bin/bash

- name: Enabling dnsmasq service
  service:
    name: dnsmasq
    enabled: yes
    state: started 

- name: Inject dnsmasq configuration file
  template: 
    src: files/dnsmasq_conf.j2
    dest: /etc/dnsmasq.conf
    
- name: Inject hosts configuration file
  template:
    src: files/hosts.j2
    dest: /etc/hosts 

- name: Inject pxelinux configuration file
  template:
    src: files/lpxelinux_0.j2
    dest: /var/www/html/rhcos/lpxelinux.0

- name: Restarting dnsmasq service
  service:
    name: dnsmasq
    state: restarted

