#-------------------------------------------------------------------------------------------#
# Ansible Playbook for registering a host and updating the system
# https://github.com/rovandep/ocp4-lab
#-------------------------------------------------------------------------------------------#
---
- include: redhat.yaml
  when: ansible_distribution == 'Red Hat Enterprise Linux'
    
- name: Update system
  yum:
    name: "*"
    state: latest

- name: Install all required packages for Infra Services VM
  yum:
    name: 
      - dnsmasq
      - httpd
      - haproxy
      - syslinux
      - tftp-server
    state: latest

- name: Configure firewall for httpd
  firewalld: 
    zone: public
    service: "{{ item }}"
    state: enabled
    immediate: yes 
    permanent: true
  with_items: [dns,dhcp,http,tftp]
