#-------------------------------------------------------------------------------------------#
# Ansible Playbook for registering a host and updating the system
# https://github.com/rovandep/ocp4-lab
#-------------------------------------------------------------------------------------------#
---
- include: redhat.yaml
  when: 
    - ansible_distribution == 'Red Hat Enterprise Linux' 
    - rhn_user is undefined
    
- name: Update system
  yum:
    name: "*"
    state: latest

- name: Install all required packages for Infra Services VM
  yum:
    name: 
      - dnsmasq
      - httpd
      - haproxy
      - syslinux
      - tftp-server
    state: latest

- name: Configure firewall with standard services (dns, dhcp, tftp, http, https)
  firewalld: 
    zone: public
    service: "{{ item }}"
    state: enabled
    immediate: yes 
    permanent: true
  with_items: [dns,dhcp,http,https,tftp]

- name: Configure firewall with custom port definitions (8080,6443,22623)
  firewalld:
    zone: public
    port: "{{ item }}/tcp"
    state: enabled
    immediate: yes
    permanent: true
  with_items: [8080,6443,22623]

  